# Generated by Django 3.0.3 on 2020-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200222_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='profile_header',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
