# Generated by Django 3.0.3 on 2020-02-23 11:28

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200223_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '144x144', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
