# Generated by Django 3.0.3 on 2020-02-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
