# Generated by Django 3.0.3 on 2020-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200223_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='link',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
